name: fe_lab_clinicas

packages:
  - apps/*
  - packages/*

scripts:
  analyze:
    run: |
      melos exec -c 1 -- fvm dart analyze . --fatal-infos
    description: |
      Run `dart analyze` in all packages.

  test:
    run: |
      melos exec -c 6 --fail-fast -- fvm flutter test --no-pub
    description: Run `flutter test` for a specific package.
    packageFilters:
      dirExists:
        - test

  test:all:
    run: |
      melos run test --no-select
    description: |
      Run all tests available.
