name: Json Rest Server
port: 8080
host: 0.0.0.0
database: database.json
enableSocket: true
socketPort: 8081
broadcastProvider: socket
idType: uuid

auth:
  jwtSecret: cwsMXDtuP447WZQ63nM4dWZ3RppyMl
  jwtExpire: 3600
  urlSkip:
    - /images/:
        method: get
    # - /users:
    #     method: post
    # - /adm_users:
    #     method: post
